### ISSUE TITLE
Functionality / Expansion

### ISSUE THREAD

**Issue by TzZek** [protodevsystems/python-pdf-splitter-extractor-and-renamer#1]
Could this be extended or modified so example:
 I have a a directory of say 500 pdfs
 I want it to take: 

- First Name: John 
- Last Name: Doe
- ID # 
- Rename each file based on those 3 specified values
- example name john_doe_112233.pdf

**Comment by protodevsystems** [comment]
Hi TzZek,

Do you mean that you have like 500 pdfs, where:
1. Each PDF has 1 (single) record of a person (not multiple records in 1 pdf)
2. Each PDF has a standardized format inside it where it has the First Name, Last Name and ID#
3. Each PDF originally has a different filename and you want to rename it as such: john_doe_112233.pdf
** or perhaps keep the original file sets, and just create a new directory for the new ones (safer)
?
Is this the scenario? If yes, then yes it is doable. You may give me a sample set of PDF to parse so I can put it in another project repo as this repo is for multiple records in a PDF (thus the "splitter" in the name). Your requirement is just having the extractor/parser and renaming parts of the code.

**Comment by TzZek** [comment]
> Hi TzZek,
> 
> Do you mean that you have like 500 pdfs, where:
> 
> 1. Each PDF has 1 (single) record of a person (not multiple records in 1 pdf)
> 2. Each PDF has a standardized format inside it where it has the First Name, Last Name and ID#
> 3. Each PDF originally has a different filename and you want to rename it as such: john_doe_112233.pdf
>    ** or perhaps keep the original file sets, and just create a new directory for the new ones (safer)
>    ?
>    Is this the scenario? If yes, then yes it is doable. You may give me a sample set of PDF to parse so I can put it in another project repo as this repo is for multiple records in a PDF (thus the "splitter" in the name). Your requirement is just having the extractor/parser and renaming parts of the code.

Yes as in there is multiple cases where the PDF might change, I was working on something like this then ran across your Repo. The PDF's in a "set" say of 500, may change over time but the same 500 would be in a given directory. 
Each filename will have some rough different name and I'd like to extract the first name, last name, and ID to the file name john_doe_112233.pdf in another directory as mentioned for safety reasons. I had extracted all the text from the PDF but was trying to figure out how to allow the user to set "variables" based on what they needed from the file for the rename.

I can get a PDF later this week unf do not have them on hand.

**Comment by protodevsystems** [comment]
The search for keywords and their positions vary on the format of that PDF. So getting that specific PDF would help me narrow down on the strategy to use in finding what is needed. Yeah I can wait. Just send them once you have them. Though I am assuming that all 500 of them are in the same format and would use the same universal strategy in parsing the data. If you are going to send me a PDF, send a couple, not just one, just to test if it works well with the others.

**Comment by TzZek** [comment]
I've gone ahead and sent you an email (from profile)

**Comment by protodevsystems** [comment]
Hi TzZek,

Requested setup is now in the new repo. 
https://github.com/protodevsystems/PDF-Parser-and-Renamer
Hope this helps!
